name: Docker CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  docker-test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install backend dependencies
        working-directory: server
        run: npm install

      - name: Run backend tests
        working-directory: server
        run: npm test

      - name: Build Docker images
        run: docker compose build


      - name: Start containers
        run: docker compose up -d
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}


      - name: Wait for server
        run: sleep 10


      - name: Test backend health
        run: curl http://localhost:3000/health


      - name: Stop containers
        run: docker compose down